version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: madhurgram-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: madhurgram-grafana
    ports:
      - "4000:3000" # Expose Grafana on port 4000 (3000 is occupied by Next.js)
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default password set to 'admin'
    depends_on:
      - prometheus
